baseURL = 'https://example.org/'
languageCode = 'en-us'
theme = 'hugo-theme-stack'
title = 'Hugo Theme Stack Starter'
copyright = 'Hugo Theme Stack Starter'

# Theme i18n support
DefaultContentLanguage = 'en'
hasCJKLanguage = false

[pagination]
pagerSize = 3

[permalinks]
post = '/p/:slug/'
page = '/:slug/'

[params]
mainSections = ['post']
featuredImageField = 'image'
rssFullContent = true

[params.footer]
since = 2020
customText = ''

[params.dateFormat]
published = 'Jan 02, 2006'
lastUpdated = 'Jan 02, 2006 15:04 MST'

[params.sidebar]
emoji = 'üç•'
subtitle = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'

[params.sidebar.avatar]
enabled = true
local = true
src = 'img/avatar.png'

[params.article]
math = false
toc = true
readingTime = true

[params.article.license]
enabled = true
default = 'Licensed under CC BY-NC-SA 4.0'

[params.comments]
enabled = false

[params.colorScheme]
toggle = true
default = 'auto'

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[[params.widgets.homepage]]
type = 'search'

[[params.widgets.homepage]]
type = 'archives'

[params.widgets.homepage.params]
limit = 5

[[params.widgets.homepage]]
type = 'categories'

[params.widgets.homepage.params]
limit = 10

[[params.widgets.homepage]]
type = 'tag-cloud'

[params.widgets.homepage.params]
limit = 10

[[params.widgets.page]]
type = 'toc'

[[menu.social]]
identifier = 'github'
name = 'GitHub'
url = 'https://github.com/CaiJimmy/hugo-theme-stack'

[menu.social.params]
icon = 'brand-github'

[[menu.social]]
identifier = 'twitter'
name = 'Twitter'
url = 'https://twitter.com'

[menu.social.params]
icon = 'brand-twitter'

[related]
includeNewer = true
threshold = 60
toLower = false

[[related.indices]]
name = 'tags'
weight = 100

[[related.indices]]
name = 'categories'
weight = 200

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
