baseURL = 'https://rationalkuma4.github.io/'
languageCode = 'en-us'
theme = 'hugo-theme-stack'
title = 'Jorge Alvarado'

# Theme i18n support
DefaultContentLanguage = 'en'
hasCJKLanguage = false

[pagination]
pagerSize = 5

[permalinks]
post = '/p/:slug/'
page = '/:slug/'

[params]
mainSections = ['post']
featuredImageField = 'image'
rssFullContent = true

[params.footer]
customText = ''

[params.dateFormat]
published = 'Jan 02, 2006'
lastUpdated = 'Jan 02, 2006 15:04 MST'

[params.sidebar]
subtitle = 'Hello there!'

[params.sidebar.avatar]
enabled = true
local = true
src = 'img/avatar.png'

[params.article]
math = true
toc = true
readingTime = true

[params.article.license]
enabled = false
default = 'Licensed under CC BY-NC-SA 4.0'

[params.comments]
enabled = false

[params.colorScheme]
toggle = true
default = 'auto'

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[[params.widgets.homepage]]
type = 'search'

[[params.widgets.homepage]]
type = 'archives'

[params.widgets.homepage.params]
limit = 5

[[params.widgets.homepage]]
type = 'categories'

[params.widgets.homepage.params]
limit = 10

[[params.widgets.page]]
type = 'toc'

[[menu.social]]
identifier = 'github'
name = 'GitHub'
url = 'https://github.com/RationalKuma4'

[menu.social.params]
icon = 'brand-github'

[[menu.social]]
identifier = 'x'
name = 'X'
url = 'https://x.com/AnselmoAlBl'

[menu.social.params]
icon = 'brand-twitter'

[[menu.social]]
identifier = 'linkedin'
name = 'LinkedIn'
url = 'https://www.linkedin.com/in/jorge-anselmo-alvarado-balbuena-1045b2191/'

[menu.social.params]
icon = 'brand-linkedin'

[related]
includeNewer = true
threshold = 50
toLower = false

[[related.indices]]
name = 'tags'
weight = 100

[[related.indices]]
name = 'categories'
weight = 100

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
